openapi: 3.0.0
info:
  version: 0.1.0
  title: Defines non-User schemas for RoadmapsFTW
paths:
  /login:
    post:
      summary: Authenticate via JWT or Facebook and hydrate the app
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
servers:
  - url: /api/v1
    description: Local development server
components:
  schemas:
    Login:
      type: object
      properties:
        username:
          type: string
          description: Username of user attempting to log in
        password:
          type: string
          description: Password of user attemptingt to log in
    UserFull:
      x-orim-update: User
      allOf:
        - $ref: '#/components/schemas/UserCreate'
        - type: object
          properties:
            user_id:
              type: string
              x-orim-model-id: true
              description: Unique User Identifier
              readOnly: true
              example: 'UserID1'
    UserCreate:
      type: object
      x-orim-create: User
      description: User
      required:
        - username
      properties:
        username:
          type: string
          description: Login user name
          example: 'testing'
          minLength: 4
          maxLength: 32
        email:
          type: string
          description: E-Mail address for user
          pattern: /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
          example: 'testing@gmail.com'
        password:
          type: string
          example: '123456'
          description: Password for user
          x-orim-create-only: true
    Roadmap:
      x-orim-create: Roadmap
      description: Roadmap
      required:
        - name
        - short_desc
      properties:
        roadmap_id:
          type: string
          x-orim-model-id: true
          description: Unique Identifier (UUID) for the roadmap
          readOnly: true
          example: Roadmap1
        name:
          type: string
          description: Name of the roadmap item
          minLength: 4
          maxLength: 40
          example: Product Release 1.0
        record_created:
          type: string
          format: date
          description: Date this record was created
          example: '2019-01-05T00:00:00.000Z'
          readOnly: true
          x-orim-base-object: true
        short_desc:
          type: string
          description: Short description of the roadmap item
          minLength: 8
          maxLength: 80
          example: First release of our new product!
        data:
          type: object
          nullable: false
          description: Application defined data associated with roadmap item
          example:
            roadmap_items: ['RoadmapItem1']
    RoadmapItem:
      x-orim-create: RoadmapItem
      description: Roadmap item
      required:
        - name
        - short_desc
      properties:
        roadmap_item_id:
          type: string
          description: Unique Identifier (UUID) for the roadmap item
          x-orim-model-id: true
          readOnly: true
          example: RoadmapItem1
        roadmap_sequence_id:
          type: number
          description: Sequence number for this version of the roadmap item
          readOnly: true
          example: 10
        name:
          type: string
          description: Name of the roadmap item
          minLength: 4
          maxLength: 40
          example: Product Release 1.0
        start_date:
          type: string
          description: Date this roadmap item begins execution
          format: date
          nullable: true
          example: '1975-08-19T00:00:00.000Z'
        release_date:
          type: string
          description: Date this roadmap item is expected to release
          format: date
          nullable: true
          example: '2019-03-31T00:00:00.000Z'
        code_coverage:
          type: number
          description: Field to test exclusiveMinimum and exclusiveMaximum
          minimum: 10
          maximum: 20
          exclusiveMinimum: true
          exclusiveMaximum: true
          example: 11
        code_coverage2:
          type: string
          description: Field to test no example
          nullable: true
        record_created:
          type: string
          format: date
          description: Date this record was created
          example: '2019-01-05T00:00:00.001Z'
          readOnly: true
          x-orim-base-object: true
        roadmap_status:
          type: string
          description: Status of this item on the roadmap
          enum:
            - Released
            - Planned
            - Targeted
            - Visionary
          example: Released
        code_name:
          type: string
          description: Code name for this roadmap item
          minLength: 3
          maxLength: 20
          example: Junky Stuff
        execution_color:
          type: string
          description: Execution color for this roadmap item
          nullable: true
          enum:
            - Red
            - Yellow
            - Green
          example: Green
        execution_status:
          type: string
          description: Brief description of execution status
          maxLength: 1024 
          nullable: true
          example: We are really, really behind schedule!
        short_desc:
          type: string
          description: Short description of the roadmap item
          minLength: 8
          maxLength: 80
          example: First release of our new product!
        data:
          type: object
          nullable: false
          description: Application defined data associated with roadmap item
          example:
            datasheet_url: https://example.com/MyDatasheet.pdf
    Tag:
      x-orim-create: Tag
      description: Tag
      required:
        - name
        - type
        - owner
      properties:
        tag_id:
          type: string
          description: Unique Identifier (UUID) for the tag
          x-orim-model-id: true
          readOnly: true
          example: Tag1
        name:
          type: string
          description: Name of the tag
          minLength: 3
          maxLength: 20
          example: FlexPod
        type:
          type: string
          description: Groups tags type of tag (used in RBAC)
          enum:
            - Application
            - Organization
            - Business Unit
            - Group
            - User
          example: User
        owner:
          type: string
          description: Identifies the user ID or RBAC role who owns the tag
          minLength: 4
          maxLength: 40
          example: User1
        short_desc:
          type: string
          description: Short description of the tag
          minLength: 3
          maxLength: 40
          example: FlexPod Solutions
          nullable: true
        record_created:
          type: string
          format: date
          example: '2019-01-05T00:00:00.002Z'
          description: Date this record was created
          readOnly: true
          x-orim-base-object: true


